### ISSUE TITLE
The circle is misaligned when run in older displays

### ISSUE THREAD

**Issue by rmvz3** [mtonio91/AMSmoothAlert#1]
The circle and the animation are misaligned when the alert run in an iPhone 4

![captura de pantalla de simulador ios 03 05 2014 23 46 58](https://cloud.githubusercontent.com/assets/674750/2871446/7959c9ee-d30c-11e3-9f99-4c453893fd3d.png)

**Comment by ahmad-atef-zz** [comment]
Yup, this is right.
but nice control :)

**Comment by mtonio91** [comment]
Fixed :) There was an mistake in the y circle position ( used screen witdth instead of height wich make no sense !)
