### ISSUE TITLE
Cocoapods GPUImage

### ISSUE THREAD

**Issue by badeleux** [mtonio91/AMSmoothAlert#19]
Why in cocoapodspec you've added GPUImage framework if you have previously marked it as dependency, and resolving this dependency leads to downloading source of GPUImage, not framework.

**Comment by natanrolnik** [comment]
What is the fix for this?

**Comment by badeleux** [comment]
Removing GPUImage from frameworks list

**Comment by mtonio91** [comment]
Hi, i can't currently update the pod on cocoapods because of their "trunk" new feature which will be available next week http://blog.cocoapods.org/CocoaPods-Trunk/  

pull requests to update pods are currently disabled that's why
https://twitter.com/CocoaPods/status/468786073477591041

**Comment by RobinQu** [comment]
After I `pod install` AMSmoothAlert (1.0), the build failed with:

```
ld: framework not found GPUImage
```

**Comment by badeleux** [comment]
It is why I asked about removing gpuimage from dependency. You have two solutions for now:
1. Provide your own spec.
2. Don't exclude Pods from git repository and manualy remove all refernces about GPUImage fw.

**Comment by lennartstolz** [comment]
Is this trunk feature still not running?

**Comment by mtonio91** [comment]
Fixed : removed gpuimage from frameworks
Thank you
