### ISSUE TITLE
Pod install warning/error

### ISSUE THREAD

**Issue by carmenalbu** [mtonio91/AMSmoothAlert#24]
[!] Unable to read the license file `[pathTo]/Pods/AMSmoothAlert/LICENSE` for the spec `AMSmoothAlert (1.0)`

Can you fix this? It seems that  tag points to a commit that does not have the LICENSE file. 

Thank you in advance,
Carmen

**Comment by carmenalbu** [comment]
And when I leave it like this and test it I get: framework not found GPUImage

**Comment by mtonio91** [comment]
https://github.com/mtonio91/AMSmoothAlert/issues/19 is the same issue, i'm going to fix this. I'll let you know when it will be done.

**Comment by mtonio91** [comment]
Fixed. Let me know if you get other issues ;)

**Comment by purepure** [comment]
I still got that error:
[!] Unable to read the license file `MyProject/Pods/AMSmoothAlert/LICENSE` for the spec `AMSmoothAlert (1.0)`
Please fix
