### ISSUE TITLE
Compile error on iOS 8 device

### ISSUE THREAD

**Issue by normalnotebook** [mtonio91/AMSmoothAlert#30]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GPUImageiOSBlurFilter", referenced from:
      objc-class-ref in AMSmoothAlertView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fprosper** [comment]
I have the same issue, do you plan to fix this? Thanks!

**Comment by kajensen** [comment]
does anyone have a solution to this?

**Comment by ghost** [comment]
I have the same issue too.

**Comment by ghost** [comment]
I fixed it finally,  just use cocoapods.
