### ISSUE TITLE
GPUImage.framework

### ISSUE THREAD

**Issue by evliu** [mtonio91/AMSmoothAlert#4]
I just tried it with the newest GPUImage framework and it works except the check mark doesn't appear after the alert drops. Tested on my 5s. Maybe just need to update the framework? Or are there other issues I'm not familiar with?

**Comment by mtonio91** [comment]
The check mark doesn't need GPUImage to be triggered. I'll try to figure out what's your issue.
Note that i'm currently pushing the repo through cocoapods, so the GPUImage dependency may be better managed.

**Comment by evliu** [comment]
figured it out; the assets were not part of the Pod Spec.
Works with 5s and newest gen iPod Touch 32gb

**Comment by mtonio91** [comment]
i think it has no link because with the pod spec because i've merged it to cocoapods after your comment :) 

glad you've fixed it !
