### ISSUE TITLE
Planned delegates

### ISSUE THREAD

**Issue by evliu** [mtonio91/AMSmoothAlert#8]
Did you plan on adding delegates in place of ones like
`-(void)alertView:(UIAlertView *)alertView didDismissWithButtonIndex:(NSInteger)buttonIndex;`? Thx!

**Comment by kkotar** [comment]
+1

**Comment by evliu** [comment]
added a pull request here:
https://github.com/mtonio91/AMSmoothAlert/pull/10
I just realized I forgot to dismiss the view as well, thus not following the name of the function, haha...
Just gotta `[self dismissAlertView]` as the first function inside the `handleButtonTouched` method and remove the else statement

**Comment by evliu** [comment]
#11
